import * as SQLite from 'expo-sqlite';

async function setupDatabase() {
  const db = await SQLite.openDatabaseAsync('gakusai_db.db');

  // Creates User Table
  createUserTable(db);

  // Creates Notecard Table
  // createNotecardTable(db);

  await db.execAsync('DROP TABLE IF EXISTS Notecard');

  // print tables
  const tables = await db.getAllAsync("SELECT * FROM sqlite_master WHERE type='table'");
  console.log('DB contents:', tables);

  return db;
}

async function createUserTable(db: SQLite.SQLiteDatabase) {
  await db.execAsync(
    `
    CREATE TABLE IF NOT EXISTS User (
      userID            INTEGER         PRIMARY KEY AUTOINCREMENT,
      username          TEXT            NOT NULL,
      apiKey            TEXT            
    );
    `
  );
}

async function createNotecardTable(db: SQLite.SQLiteDatabase) {
  await db.execAsync(
    `
    CREATE TABLE IF NOT EXISTS Notecard (
      notecardID        INTEGER         PRIMARY KEY AUTOINCREMENT,
      category          TEXT            NOT NULL,
      englishText       TEXT            NOT NULL,
      romajiText        TEXT            NOT NULL,
      japaneseText      TEXT            NOT NULL
    );
    `
    // Scripts: Hiragana, Katakana, Kanji, Mixed
    // Categories: Kana/Letter, Kotoba/Word, 
  );
}

async function createNotecardScriptTable(db: SQLite.SQLiteDatabase) {
  await db.execAsync(
    `
    CREATE TABLE IF NOT EXISTS NotecardScript (
      notecardScriptID  INTEGER        PRIMARY KEY AUTOINCREMENT,
      scriptName        TEXT           NOT NULL
    );
    `
  );
}

// Since Notecard, and Notecard Category have a many-many relationship, an additional junction/join table is needed for both
async function createNoteCategoryJunctionTable(db: SQLite.SQLiteDatabase) {
  await db.execAsync(
    `
    CREATE TABLE IF NOT EXISTS NotecardScriptJunction (
      notecardID        INTEGER         NOT NULL,
      notecardScriptID  INTEGER         NOT NULL,
      PRIMARY KEY (notecardID, notecardScriptID),
      FOREIGN KEY (notecardID)          REFERENCES Notecard(notecardID),
      FOREIGN KEY (notecardScriptID)    REFERENCES NotecardScript(notecardScriptID)
    );
    `
  );
}

// Maybe make it so in the japaneseText field, make the AI replace any kanji is replaced with something like [FURIGANA], and the AI will instead store the kanji + kana in a separate Furigana table
// Then, for each Furigana entry tied to the notecard, loop through each furiganaID and replace any instances of [FURIGANA] before inserting it into the final notecard

// Or, maybe?? we don't even need to replace the kanji with [FURIGANA]
// Example of ruby in HTML (word: Kan ji):
// <ruby>
//   漢 <rp>(</rp><rt>Kan</rt><rp>)</rp> 字 <rp>(</rp><rt>ji</rt><rp>)</rp>
// </ruby>
async function createFuriganaTable(db: SQLite.SQLiteDatabase) {
  await db.execAsync(
    `
    CREATE TABLE IF NOT EXISTS Furigana (
      furiganaID        INTEGER         PRIMARY KEY AUTOINCREMENT,
      notecardID        INTEGER         NOT NULL,
      kana              TEXT            NOT NULL,
      kanji             TEXT            NOT NULL,
      FOREIGN KEY (notecardID)          REFERENCES Notecard(notecardID)
    );
    `
  )
}

// NOTE: Actually, there's a way to display Furigana called "ruby text"
// async function createFuriganaTable(db: SQLite.SQLiteDatabase) {
//   await db.execAsync(
//     `
//     CREATE TABLE IF NOT EXISTS Furigana (
//       furiganaID        INTEGER         PRIMARY KEY AUTOINCREMENT,
//       notecardID        INTEGER         NOT NULL,
//       k
//     );
//     `
//   )
// }

export default setupDatabase;
 // Generated by Claude. Testing database setup, rewrite later

 // To run, open project in terminal, then run: npx expo start